<?php
"CREATE TABLE IF NOT EXISTS webhooks (
id int NOT NULL AUTO_INCREMENT,
partner_id int NOT NULL,
partner_user_id int NOT NULL,
url LONGTEXT NOT NULL,
attempt TINYINT(1) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE CASCADE,
FOREIGN KEY (partner_user_id) REFERENCES partner_users(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
?>