<?php
"CREATE TABLE IF NOT EXISTS partners (
id int NOT NULL AUTO_INCREMENT,
name VARCHAR(75) NULL,
email VARCHAR(75) NOT NULL UNIQUE,
email_verified_at TIMESTAMP NULL,
api_key VARCHAR(175) NOT NULL UNIQUE,
status TINYINT(1) NOT NULL DEFAULT '1',
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
?>