<?php
"CREATE TABLE IF NOT EXISTS webhook_details (
id int NOT NULL AUTO_INCREMENT,
webhook_id int NOT NULL,
pms_response LONGTEXT NOT NULL,
cax_response LONGTEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
FOREIGN KEY (webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
?>