<?php
"CREATE TABLE IF NOT EXISTS partner_users (
id int NOT NULL AUTO_INCREMENT,
partner_id int NOT NULL,
pms_user_id  int NOT NULL, 
pms_name VARCHAR(75) NULL,
credential_token VARCHAR(175) NOT NULL UNIQUE,
credentials LONGTEXT NOT NULL,
status TINYINT(1) NOT NULL DEFAULT '1',
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
?>