<?php

const UN_AUTHORIZED = 401;
const INTERNAL_SERVER_ERROR = 500;
const DATA_NOT_FOUND = 404;

const CAX_EXCEPTION_CODES = [
    UN_AUTHORIZED => CAX_CLIENT_UNAUTHORIZED_ERROR,
    INTERNAL_SERVER_ERROR => PMS_INTERNAL_SERVER_ERROR,
    DATA_NOT_FOUND => PMS_INTERNAL_SERVER_ERROR,

];
