<?php

require_once __DIR__ . '/../../../const/booking_sources_const.php';

return [
    '30A Home Rentals' => HOME_RENTALS_30A,
    'Agoda' => AGODA,
    'Airbnb' => AIRBNB,
    'Alabama Vacation Home Rentals' => ALABAMA_VACATION_HOME_RENTALS,
    'Arrange Your Vacation' => ARRANGE_YOUR_VACATION,
    'Big Bridge Travel' => BIG_BRIDGE_TRAVEL,
    'Booking.com' => BOOKING_DOT_COM,
    'Boutique Homes' => BOUTIQUE_HOMES,
    'California Vacation Rentals' => CALIFORNIA_VACATION_RENTALS,
    'Canada Stays' => CANADA_STAYS,
    'Carolina Vacation Home Rentals' => CAROLINA_VACATION_HOME_RENTALS,
    'CastleCave' => CASTLE_CAVE,
    'Colorado Vacation Homes' => COLORADO_VACATION_HOMES,
    'Cattages in Canada' => CATTAGES_IN_CANADA,
    'Emerald Coast By Owner' => EMERALD_COAST_BY_OWNER,
    'Expedia' => EXPEDIA,
    'Facebook' => FACEBOOK,
    'Find Rentals' => FIND_RENTALS,
    'Florida Rental By Owners' => FLORIDA_RENTAL_BY_OWNERS,
    'Florida Rentals' => FLORIDA_RENTALS,
    'FreeVacationRentalSite.com' => FREE_VACATION_RENTAL_SITE_DOT_COM,
    'GetAwayDigs.com' => GET_AWAY_DIGS_DOT_COM,
    'getawayGoGo' => GET_AWAY_GO_GO,
    'Glamping Hub' => GLAMPING_HUB,
    'Golightly' => GOLIGHTL,
    'GuestSmiles' => GUEST_SMILES,
    'Hawaiian Islands Vacation Rentals' => HAWAIIAN_ISLANDS_VACATION_RENTALS,
    'HA-XML Sandbox' => HA_XML_SANDBOX,
    'Holiday Lettings' => HOLIDAY_LETTINGS,
    'HomeEscape' => HOME_ESCAPE,
    'HomeToGo' => HOME_TO_GO,
    'Houfy' => HOUFY,
    'MD/DE Vacation Rentals By Owners' => MD_DE_VACATION_RENTALS_BY_OWNERS,
    'New York Rental By Owner' => NEW_YORK_RENTAL_BY_OWNER,
    'Owner Block-Off' => OWNER_BLOCK_OFF,
    'Perfect Places' => PERFECT_PLACES,
    'Referral' => REFERRAL,
    'RentalBug.com' => RENTAL_BUG_DOT_COM,
    'Sayulita Life' => SAYULITA_LIFE,
    'Shenandoah Cabin Rentals' => SHENANDOAH_CABIN_RENTALS,
    'Smoky Mountains by Owners' => SMOKY_MOUNTAINS_BY_OWNERS,
    'SmokyMountains.com' => SMOKY_MOUNTAINS_DOT_COM,
    'Spain Holiday A.L.' => SPAIN_HOLIDAY_A_L,
    'Tennessee Rentals By Owner' => TENNESSEE_RENTALS_BY_OWNER,
    'TexEscapes' => TEX_ESCAPES,
    'TripAdvisor' => TRIP_ADVISOR,
    'USVI Vacation Homes' => USVI_VACATION_HOMES,
    'Vacation Home Rentals' => VACATION_HOME_RENTALS,
    'Vacation Rentals LBI' => VACATION_RENTALS_LBI,
    'VacationRentalPeople.com' => VACATION_RENTAL_PEOPLE_DOT_COM,
    'VacationRentals.com' => VACATION_RENTALS_DOT_COM,
    'VastTrips' => VAST_TRIPS,
    'Virginia Vacation Rentals' => VIRGINIA_VACATION_RENTALS,
    'Vrbo' => VRBO,
    'VRWD' => VRWD,
    'Whimstay' => WHIMSTAY,

    '3 Channel Bridge' => THREE_CHANNEL_BRIDGE,
    'Hawaii.so (old)' => HAWAII_DOT_SO_OLD,
    'Hawaii.so (oahu)' => HAWAII_DOT_SO_OAHU,
    'My Website' => MY_WEBSITE,
    'Oahu.Hostably.com' => OAHU_DOT_HOSTABLY_DOT_COM,
    'kushkations.com' => KUSHKATIONS_DOT_COM,
    'allexclusivebnb.com' => ALL_EXCLUSIVE_BNB_DOT_COM,
    'Lodgix' => LODGIX,
    'pammartin.hosted.ownerrez.com' => PAMMARTIN_DOT_HOSTED_DOT_OWNERREZ_DOT_COM,

    'Direct Booking - My Website' => DIRECT_BOOKING_MY_WEBSITE,
    'GrizzlyBearsResort.com' => GRIZZLY_BEARS_RESORT_DOT_COM,
    'Park City Adventure Lodging' => PARK_CITY_ADVENTURE_LODGING,
    'Owner staying' => OWNER_STAYING,
    'Bobs Travel' => BOBS_TRAVEL,

    'villaseaparadisecuracao.com' => VILLASEAPARADISECURACAO_DOT_COM,
    'Micazu' => MICAZU,
    'Huisje te Huur' => HUISJE_TE_HUUR,
    'Debbie\u2019s' => DEBBIE_U2019S,
    'ITravel Gmbh' => ITRAVEL_GMBH,
    'savvyvrm.com' => SAVVYVRM_DOT_COM,
];
