<?php
"CREATE TABLE IF NOT EXISTS query_logs (
id int NOT NULL AUTO_INCREMENT,
model VARCHAR(50) NOT NULL,
action VARCHAR(50) NOT NULL,
status VARCHAR(15) NOT NULL,
statement LONGTEXT NOT NULL,
statement_value LONGTEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
?>