<?php

const UN_AUTHORIZED = 403;
const UN_AUTHORIZED_401 = 401;

const CAX_EXCEPTION_CODES = [
    UN_AUTHORIZED => CAX_CLIENT_UNAUTHORIZED_ERROR,
    UN_AUTHORIZED_401 => CAX_CLIENT_UNAUTHORIZED_ERROR,
];
